### ISSUE TITLE
[Slidr] Error adding [horizontal] slides for [testimonials-slider].

### ISSUE THREAD

**Issue by Pestov** [bchanx/slidr#52]
Hi! I can't make my slider infinitely. Console shows me warning message "[Slidr] Error adding [horizontal] slides for [testimonials-slider]". What does it mean? 
```
slidr.create('testimonials', {
	breadcrumbs: true,
	overflow: true
}).add('horizontal', ['one', 'two', 'three', 'one']).start();

```

```
   <div class="testimonials">
      <div class="testimonials__content" id="testimonials-slider">
         <div class="testimonial" data-slidr="one">

         </div>
         <div class="testimonial" data-slidr="two">

         </div>
         <div class="testimonial" data-slidr="tree">

         </div>
      </div>
   </div>
```

**Comment by bchanx** [comment]
Hi @Pestov,

It looks like you have `data-slidr="tree"` set in your html markup instead of `data-slidr="three"`, so the library can't find the slide you're trying to animate.

Let me know if that fixes the issue.

**Comment by Pestov** [comment]
@bchanx thanks man, it works. Sorry for so stupid issue because of my inattention. I read docs more than hours, checked version and problem in "tree" and "three". Ohhhh =) 

Thanks again, slidr is cool!
